name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: floaritay
          outputs: |
            dist/github-snake-dark.svg?color_snake=purple&color_dots=#c4b5fd,#a78bfa,#8b5cf6,#7c3aed,#6d28d9
            dist/github-snake.svg

      - name: Deploy to gh-pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
